version: '3'

services:
###> doctrine/doctrine-bundle ###
#  database:
#    ports:
#      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
#  mailer:
#    image: schickling/mailcatcher
#    ports: [1025, 1080]
###< symfony/mailer ###

  mailer:
    image: mailhog/mailhog
    container_name: erc-mailer
    ports:
      - 8025:8025
