version: '3'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - 15432:5432
    volumes:
      - /var/lib/postgresql/data

  php-fpm:
    container_name: php-fpm
    build:
      context: .docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
#      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/var/www:rw

  nginx:
    container_name: nginx
    build:
      context: .docker/nginx
    volumes:
      - ./:/var/www:rw
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/sites/:/etc/nginx/sites-available
#      - ./nginx/conf.d/:/etc/nginx/conf.d
#      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "808:80"
      - "444:443"

volumes:
  db-data:
